// Generated by `tools/generate-demo-model-dts.ts` — do not hand-edit.
// Stands in for the `models.d.ts` augmentation the real place editor
// generates live from a place's own attached model bytes (`model-dts.ts`,
// ADR 0050), so every built-in demo script — an ordinary source file in this
// project, not only something loaded through the editor — type-checks the
// same way any other file here does. Covers every model any built-in demo
// attaches, deduplicated, since they are all checked as part of the same
// program; a model two demos share (e.g. `counter.zip`) contributes one
// identical entry, which TypeScript's declaration merging accepts without
// conflict only because both demos read the exact same file.
declare module "voxelscape" {
  interface ModelsByName {
    bed: {
      readonly name: "bed";
      readonly file: "bed.zip";
      readonly parts: readonly "body"[];
      readonly motions: readonly never[];
    };
    bathtub: {
      readonly name: "bathtub";
      readonly file: "bathtub.zip";
      readonly parts: readonly "body"[];
      readonly motions: readonly never[];
    };
    sofa: {
      readonly name: "sofa";
      readonly file: "sofa.zip";
      readonly parts: readonly "body"[];
      readonly motions: readonly never[];
    };
    tv: {
      readonly name: "tv";
      readonly file: "tv.zip";
      readonly parts: readonly "body"[];
      readonly motions: readonly never[];
    };
    table: {
      readonly name: "table";
      readonly file: "table.zip";
      readonly parts: readonly "body"[];
      readonly motions: readonly never[];
    };
    counter: {
      readonly name: "counter";
      readonly file: "counter.zip";
      readonly parts: readonly "body"[];
      readonly motions: readonly never[];
    };
    stove: {
      readonly name: "stove";
      readonly file: "stove.zip";
      readonly parts: readonly "body"[];
      readonly motions: readonly never[];
    };
    fridge: {
      readonly name: "fridge";
      readonly file: "fridge.zip";
      readonly parts: readonly "body"[];
      readonly motions: readonly never[];
    };
    breakfastmachine: {
      readonly name: "breakfastmachine";
      readonly file: "breakfastmachine.zip";
      readonly parts: readonly "body"[];
      readonly motions: readonly never[];
    };
    freezer: {
      readonly name: "freezer";
      readonly file: "freezer.zip";
      readonly parts: readonly "body"[];
      readonly motions: readonly never[];
    };
    car: {
      readonly name: "car";
      readonly file: "car.zip";
      readonly parts: readonly "body"[];
      readonly motions: readonly never[];
    };
    toilet: {
      readonly name: "toilet";
      readonly file: "toilet.zip";
      readonly parts: readonly "body"[];
      readonly motions: readonly never[];
    };
    tree: {
      readonly name: "tree";
      readonly file: "tree.zip";
      readonly parts: readonly "body"[];
      readonly motions: readonly never[];
    };
    bench: {
      readonly name: "bench";
      readonly file: "bench.zip";
      readonly parts: readonly "body"[];
      readonly motions: readonly never[];
    };
    manhole: {
      readonly name: "manhole";
      readonly file: "manhole.zip";
      readonly parts: readonly "body"[];
      readonly motions: readonly never[];
    };
    trash: {
      readonly name: "trash";
      readonly file: "trash.zip";
      readonly parts: readonly "body"[];
      readonly motions: readonly never[];
    };
    register: {
      readonly name: "register";
      readonly file: "register.zip";
      readonly parts: readonly "body"[];
      readonly motions: readonly never[];
    };
    shelf: {
      readonly name: "shelf";
      readonly file: "shelf.zip";
      readonly parts: readonly "body"[];
      readonly motions: readonly never[];
    };
    vending: {
      readonly name: "vending";
      readonly file: "vending.zip";
      readonly parts: readonly "body"[];
      readonly motions: readonly never[];
    };
    chips: {
      readonly name: "chips";
      readonly file: "chips.zip";
      readonly parts: readonly "body"[];
      readonly motions: readonly never[];
    };
    orange: {
      readonly name: "orange";
      readonly file: "orange.zip";
      readonly parts: readonly "body"[];
      readonly motions: readonly never[];
    };
    colgate: {
      readonly name: "colgate";
      readonly file: "colgate.zip";
      readonly parts: readonly "body"[];
      readonly motions: readonly never[];
    };
    cola: {
      readonly name: "cola";
      readonly file: "cola.zip";
      readonly parts: readonly "body"[];
      readonly motions: readonly never[];
    };
    egg: {
      readonly name: "egg";
      readonly file: "egg.zip";
      readonly parts: readonly "body"[];
      readonly motions: readonly never[];
    };
    friedegg: {
      readonly name: "friedegg";
      readonly file: "friedegg.zip";
      readonly parts: readonly "body"[];
      readonly motions: readonly never[];
    };
    juice: {
      readonly name: "juice";
      readonly file: "juice.zip";
      readonly parts: readonly "body"[];
      readonly motions: readonly never[];
    };
    milk: {
      readonly name: "milk";
      readonly file: "milk.zip";
      readonly parts: readonly "body"[];
      readonly motions: readonly never[];
    };
    witchbrew: {
      readonly name: "witchbrew";
      readonly file: "witchbrew.zip";
      readonly parts: readonly "body"[];
      readonly motions: readonly never[];
    };
    hotbrew: {
      readonly name: "hotbrew";
      readonly file: "hotbrew.zip";
      readonly parts: readonly "body"[];
      readonly motions: readonly never[];
    };
    icecream: {
      readonly name: "icecream";
      readonly file: "icecream.zip";
      readonly parts: readonly "body"[];
      readonly motions: readonly never[];
    };
    candy: {
      readonly name: "candy";
      readonly file: "candy.zip";
      readonly parts: readonly "body"[];
      readonly motions: readonly never[];
    };
    fuel: {
      readonly name: "fuel";
      readonly file: "fuel.zip";
      readonly parts: readonly "body"[];
      readonly motions: readonly never[];
    };
    patty: {
      readonly name: "patty";
      readonly file: "patty.zip";
      readonly parts: readonly "body"[];
      readonly motions: readonly never[];
    };
    sandvich: {
      readonly name: "sandvich";
      readonly file: "sandvich.zip";
      readonly parts: readonly "body"[];
      readonly motions: readonly never[];
    };
    sword: {
      readonly name: "sword";
      readonly file: "sword.zip";
      readonly parts: readonly "body"[];
      readonly motions: readonly never[];
    };
    tix: {
      readonly name: "tix";
      readonly file: "tix.zip";
      readonly parts: readonly "body"[];
      readonly motions: readonly never[];
    };
    robux: {
      readonly name: "robux";
      readonly file: "robux.zip";
      readonly parts: readonly "body"[];
      readonly motions: readonly never[];
    };
    "npc-sable": {
      readonly name: "npc-sable";
      readonly file: "npc-sable.zip";
      readonly parts: readonly "body"[];
      readonly motions: readonly never[];
    };
    "npc-rook": {
      readonly name: "npc-rook";
      readonly file: "npc-rook.zip";
      readonly parts: readonly "body"[];
      readonly motions: readonly never[];
    };
    "npc-laugh": {
      readonly name: "npc-laugh";
      readonly file: "npc-laugh.zip";
      readonly parts: readonly "body"[];
      readonly motions: readonly never[];
    };
    "npc-alex": {
      readonly name: "npc-alex";
      readonly file: "npc-alex.zip";
      readonly parts: readonly "body"[];
      readonly motions: readonly never[];
    };
    "npc-james": {
      readonly name: "npc-james";
      readonly file: "npc-james.zip";
      readonly parts: readonly "body"[];
      readonly motions: readonly never[];
    };
    "npc-bully": {
      readonly name: "npc-bully";
      readonly file: "npc-bully.zip";
      readonly parts: readonly "body"[];
      readonly motions: readonly never[];
    };
    "npc-nerd": {
      readonly name: "npc-nerd";
      readonly file: "npc-nerd.zip";
      readonly parts: readonly "body"[];
      readonly motions: readonly never[];
    };
    "npc-homeless": {
      readonly name: "npc-homeless";
      readonly file: "npc-homeless.zip";
      readonly parts: readonly "body"[];
      readonly motions: readonly never[];
    };
    "npc-brit": {
      readonly name: "npc-brit";
      readonly file: "npc-brit.zip";
      readonly parts: readonly "body"[];
      readonly motions: readonly never[];
    };
    "npc-brett": {
      readonly name: "npc-brett";
      readonly file: "npc-brett.zip";
      readonly parts: readonly "body"[];
      readonly motions: readonly never[];
    };
    "npc-brad": {
      readonly name: "npc-brad";
      readonly file: "npc-brad.zip";
      readonly parts: readonly "body"[];
      readonly motions: readonly never[];
    };
    "npc-sleepa": {
      readonly name: "npc-sleepa";
      readonly file: "npc-sleepa.zip";
      readonly parts: readonly "body"[];
      readonly motions: readonly never[];
    };
    "npc-champ": {
      readonly name: "npc-champ";
      readonly file: "npc-champ.zip";
      readonly parts: readonly "body"[];
      readonly motions: readonly never[];
    };
    "npc-teacher": {
      readonly name: "npc-teacher";
      readonly file: "npc-teacher.zip";
      readonly parts: readonly "body"[];
      readonly motions: readonly never[];
    };
    "npc-lemonade": {
      readonly name: "npc-lemonade";
      readonly file: "npc-lemonade.zip";
      readonly parts: readonly "body"[];
      readonly motions: readonly never[];
    };
    "npc-pothead": {
      readonly name: "npc-pothead";
      readonly file: "npc-pothead.zip";
      readonly parts: readonly "body"[];
      readonly motions: readonly never[];
    };
    "npc-santa": {
      readonly name: "npc-santa";
      readonly file: "npc-santa.zip";
      readonly parts: readonly "body"[];
      readonly motions: readonly never[];
    };
    "npc-obby": {
      readonly name: "npc-obby";
      readonly file: "npc-obby.zip";
      readonly parts: readonly "body"[];
      readonly motions: readonly never[];
    };
    "npc-littlebro": {
      readonly name: "npc-littlebro";
      readonly file: "npc-littlebro.zip";
      readonly parts: readonly "body"[];
      readonly motions: readonly never[];
    };
    "npc-anomaly": {
      readonly name: "npc-anomaly";
      readonly file: "npc-anomaly.zip";
      readonly parts: readonly "body"[];
      readonly motions: readonly never[];
    };
    phone: {
      readonly name: "phone";
      readonly file: "phone.zip";
      readonly parts: readonly "body"[];
      readonly motions: readonly never[];
    };
    mirror: {
      readonly name: "mirror";
      readonly file: "mirror.zip";
      readonly parts: readonly "body"[];
      readonly motions: readonly never[];
    };
    bookshelf: {
      readonly name: "bookshelf";
      readonly file: "bookshelf.zip";
      readonly parts: readonly "body"[];
      readonly motions: readonly never[];
    };
    door: {
      readonly name: "door";
      readonly file: "door.zip";
      readonly parts: readonly "body"[];
      readonly motions: readonly never[];
    };
    mailbox: {
      readonly name: "mailbox";
      readonly file: "mailbox.zip";
      readonly parts: readonly "body"[];
      readonly motions: readonly never[];
    };
    "lemonade-stand": {
      readonly name: "lemonade-stand";
      readonly file: "lemonade-stand.zip";
      readonly parts: readonly "body"[];
      readonly motions: readonly never[];
    };
    "bus-stop": {
      readonly name: "bus-stop";
      readonly file: "bus-stop.zip";
      readonly parts: readonly "body"[];
      readonly motions: readonly never[];
    };
    flower: {
      readonly name: "flower";
      readonly file: "flower.zip";
      readonly parts: readonly "body"[];
      readonly motions: readonly never[];
    };
    gate: {
      readonly name: "gate";
      readonly file: "gate.zip";
      readonly parts: readonly "body"[];
      readonly motions: readonly never[];
    };
    "slushie-machine": {
      readonly name: "slushie-machine";
      readonly file: "slushie-machine.zip";
      readonly parts: readonly "body"[];
      readonly motions: readonly never[];
    };
    arcade: {
      readonly name: "arcade";
      readonly file: "arcade.zip";
      readonly parts: readonly "body"[];
      readonly motions: readonly never[];
    };
    "boarded-machine": {
      readonly name: "boarded-machine";
      readonly file: "boarded-machine.zip";
      readonly parts: readonly "body"[];
      readonly motions: readonly never[];
    };
    dumpster: {
      readonly name: "dumpster";
      readonly file: "dumpster.zip";
      readonly parts: readonly "body"[];
      readonly motions: readonly never[];
    };
    desk: {
      readonly name: "desk";
      readonly file: "desk.zip";
      readonly parts: readonly "body"[];
      readonly motions: readonly never[];
    };
    chair: {
      readonly name: "chair";
      readonly file: "chair.zip";
      readonly parts: readonly "body"[];
      readonly motions: readonly never[];
    };
    locker: {
      readonly name: "locker";
      readonly file: "locker.zip";
      readonly parts: readonly "body"[];
      readonly motions: readonly never[];
    };
    "cafeteria-table": {
      readonly name: "cafeteria-table";
      readonly file: "cafeteria-table.zip";
      readonly parts: readonly "body"[];
      readonly motions: readonly never[];
    };
    plate: {
      readonly name: "plate";
      readonly file: "plate.zip";
      readonly parts: readonly "body"[];
      readonly motions: readonly never[];
    };
    poster: {
      readonly name: "poster";
      readonly file: "poster.zip";
      readonly parts: readonly "body"[];
      readonly motions: readonly never[];
    };
    plush: {
      readonly name: "plush";
      readonly file: "plush.zip";
      readonly parts: readonly "body"[];
      readonly motions: readonly never[];
    };
    banana: {
      readonly name: "banana";
      readonly file: "banana.zip";
      readonly parts: readonly "body"[];
      readonly motions: readonly never[];
    };
    key: {
      readonly name: "key";
      readonly file: "key.zip";
      readonly parts: readonly "body"[];
      readonly motions: readonly never[];
    };
    matches: {
      readonly name: "matches";
      readonly file: "matches.zip";
      readonly parts: readonly "body"[];
      readonly motions: readonly never[];
    };
    slushie: {
      readonly name: "slushie";
      readonly file: "slushie.zip";
      readonly parts: readonly "body"[];
      readonly motions: readonly never[];
    };
    pizza: {
      readonly name: "pizza";
      readonly file: "pizza.zip";
      readonly parts: readonly "body"[];
      readonly motions: readonly never[];
    };
    hotdog: {
      readonly name: "hotdog";
      readonly file: "hotdog.zip";
      readonly parts: readonly "body"[];
      readonly motions: readonly never[];
    };
    salad: {
      readonly name: "salad";
      readonly file: "salad.zip";
      readonly parts: readonly "body"[];
      readonly motions: readonly never[];
    };
    taco: {
      readonly name: "taco";
      readonly file: "taco.zip";
      readonly parts: readonly "body"[];
      readonly motions: readonly never[];
    };
    historybook: {
      readonly name: "historybook";
      readonly file: "historybook.zip";
      readonly parts: readonly "body"[];
      readonly motions: readonly never[];
    };
    roaster: {
      readonly name: "roaster";
      readonly file: "roaster.zip";
      readonly parts: readonly "body"[];
      readonly motions: readonly never[];
    };
    hat: {
      readonly name: "hat";
      readonly file: "hat.zip";
      readonly parts: readonly "body"[];
      readonly motions: readonly never[];
    };
    lemonade: {
      readonly name: "lemonade";
      readonly file: "lemonade.zip";
      readonly parts: readonly "body"[];
      readonly motions: readonly never[];
    };
    foodbag: {
      readonly name: "foodbag";
      readonly file: "foodbag.zip";
      readonly parts: readonly "body"[];
      readonly motions: readonly never[];
    };
    bean: {
      readonly name: "bean";
      readonly file: "bean.zip";
      readonly parts: readonly "body"[];
      readonly motions: readonly never[];
    };
    zombie: {
      readonly name: "zombie";
      readonly file: "zombie.zip";
      readonly parts: readonly "body"[];
      readonly motions: readonly never[];
    };
    soap: {
      readonly name: "soap";
      readonly file: "soap.zip";
      readonly parts: readonly "body"[];
      readonly motions: readonly never[];
    };
    "wet-floor": {
      readonly name: "wet-floor";
      readonly file: "wet-floor.zip";
      readonly parts: readonly "body"[];
      readonly motions: readonly never[];
    };
    platform: {
      readonly name: "platform";
      readonly file: "platform.zip";
      readonly parts: readonly "body"[];
      readonly motions: readonly never[];
    };
    "toilet-roll": {
      readonly name: "toilet-roll";
      readonly file: "toilet-roll.zip";
      readonly parts: readonly "body"[];
      readonly motions: readonly never[];
    };
    "gas-pump": {
      readonly name: "gas-pump";
      readonly file: "gas-pump.zip";
      readonly parts: readonly "body"[];
      readonly motions: readonly never[];
    };
    "npc-sweep": {
      readonly name: "npc-sweep";
      readonly file: "npc-sweep.zip";
      readonly parts: readonly "body"[];
      readonly motions: readonly never[];
    };
    "npc-playtime": {
      readonly name: "npc-playtime";
      readonly file: "npc-playtime.zip";
      readonly parts: readonly "body"[];
      readonly motions: readonly never[];
    };
    "npc-principal": {
      readonly name: "npc-principal";
      readonly file: "npc-principal.zip";
      readonly parts: readonly "body"[];
      readonly motions: readonly never[];
    };
    "npc-puppet": {
      readonly name: "npc-puppet";
      readonly file: "npc-puppet.zip";
      readonly parts: readonly "body"[];
      readonly motions: readonly never[];
    };
    "npc-prize": {
      readonly name: "npc-prize";
      readonly file: "npc-prize.zip";
      readonly parts: readonly "body"[];
      readonly motions: readonly never[];
    };
    "cave-yellowhand": {
      readonly name: "cave-yellowhand";
      readonly file: "cave-yellowhand.zip";
      readonly parts: readonly "body"[];
      readonly motions: readonly never[];
    };
    "cave-wormle": {
      readonly name: "cave-wormle";
      readonly file: "cave-wormle.zip";
      readonly parts: readonly "body"[];
      readonly motions: readonly never[];
    };
    "cave-poopie": {
      readonly name: "cave-poopie";
      readonly file: "cave-poopie.zip";
      readonly parts: readonly "body"[];
      readonly motions: readonly never[];
    };
    "cave-chik": {
      readonly name: "cave-chik";
      readonly file: "cave-chik.zip";
      readonly parts: readonly "body"[];
      readonly motions: readonly never[];
    };
    "cave-megachik": {
      readonly name: "cave-megachik";
      readonly file: "cave-megachik.zip";
      readonly parts: readonly "body"[];
      readonly motions: readonly never[];
    };
    "cave-ninja": {
      readonly name: "cave-ninja";
      readonly file: "cave-ninja.zip";
      readonly parts: readonly "body"[];
      readonly motions: readonly never[];
    };
    "cave-chest": {
      readonly name: "cave-chest";
      readonly file: "cave-chest.zip";
      readonly parts: readonly "body"[];
      readonly motions: readonly never[];
    };
    "cave-boss-chest": {
      readonly name: "cave-boss-chest";
      readonly file: "cave-boss-chest.zip";
      readonly parts: readonly "body"[];
      readonly motions: readonly never[];
    };
    "cave-coin": {
      readonly name: "cave-coin";
      readonly file: "cave-coin.zip";
      readonly parts: readonly "body"[];
      readonly motions: readonly never[];
    };
    "cave-key": {
      readonly name: "cave-key";
      readonly file: "cave-key.zip";
      readonly parts: readonly "body"[];
      readonly motions: readonly never[];
    };
    "cave-torch": {
      readonly name: "cave-torch";
      readonly file: "cave-torch.zip";
      readonly parts: readonly "body"[];
      readonly motions: readonly never[];
    };
    "cave-craft": {
      readonly name: "cave-craft";
      readonly file: "cave-craft.zip";
      readonly parts: readonly "body"[];
      readonly motions: readonly never[];
    };
    "cave-lifeplant": {
      readonly name: "cave-lifeplant";
      readonly file: "cave-lifeplant.zip";
      readonly parts: readonly "body"[];
      readonly motions: readonly never[];
    };
    "cave-hat": {
      readonly name: "cave-hat";
      readonly file: "cave-hat.zip";
      readonly parts: readonly "body"[];
      readonly motions: readonly never[];
    };
    "cave-sign": {
      readonly name: "cave-sign";
      readonly file: "cave-sign.zip";
      readonly parts: readonly "body"[];
      readonly motions: readonly never[];
    };
    floppa: {
      readonly name: "floppa";
      readonly file: "floppa.zip";
      readonly parts: readonly "body"[];
      readonly motions: readonly never[];
    };
    "ms-floppa": {
      readonly name: "ms-floppa";
      readonly file: "ms-floppa.zip";
      readonly parts: readonly "body"[];
      readonly motions: readonly never[];
    };
    "baby-floppa": {
      readonly name: "baby-floppa";
      readonly file: "baby-floppa.zip";
      readonly parts: readonly "body"[];
      readonly motions: readonly never[];
    };
    "elder-floppa": {
      readonly name: "elder-floppa";
      readonly file: "elder-floppa.zip";
      readonly parts: readonly "body"[];
      readonly motions: readonly never[];
    };
    "soldier-floppa": {
      readonly name: "soldier-floppa";
      readonly file: "soldier-floppa.zip";
      readonly parts: readonly "body"[];
      readonly motions: readonly never[];
    };
    bandit: {
      readonly name: "bandit";
      readonly file: "bandit.zip";
      readonly parts: readonly "body"[];
      readonly motions: readonly never[];
    };
    bingus: {
      readonly name: "bingus";
      readonly file: "bingus.zip";
      readonly parts: readonly "body"[];
      readonly motions: readonly never[];
    };
    "neko-maid": {
      readonly name: "neko-maid";
      readonly file: "neko-maid.zip";
      readonly parts: readonly "body"[];
      readonly motions: readonly never[];
    };
    ooga: {
      readonly name: "ooga";
      readonly file: "ooga.zip";
      readonly parts: readonly "body"[];
      readonly motions: readonly never[];
    };
    "food-bowl": {
      readonly name: "food-bowl";
      readonly file: "food-bowl.zip";
      readonly parts: readonly "body"[];
      readonly motions: readonly never[];
    };
    "litter-box": {
      readonly name: "litter-box";
      readonly file: "litter-box.zip";
      readonly parts: readonly "body"[];
      readonly motions: readonly never[];
    };
    computer: {
      readonly name: "computer";
      readonly file: "computer.zip";
      readonly parts: readonly "body"[];
      readonly motions: readonly never[];
    };
    "cat-bed": {
      readonly name: "cat-bed";
      readonly file: "cat-bed.zip";
      readonly parts: readonly "body"[];
      readonly motions: readonly never[];
    };
    "scratching-post": {
      readonly name: "scratching-post";
      readonly file: "scratching-post.zip";
      readonly parts: readonly "body"[];
      readonly motions: readonly never[];
    };
    "catnip-plant": {
      readonly name: "catnip-plant";
      readonly file: "catnip-plant.zip";
      readonly parts: readonly "body"[];
      readonly motions: readonly never[];
    };
    "money-bag": {
      readonly name: "money-bag";
      readonly file: "money-bag.zip";
      readonly parts: readonly "body"[];
      readonly motions: readonly never[];
    };
    poop: {
      readonly name: "poop";
      readonly file: "poop.zip";
      readonly parts: readonly "body"[];
      readonly motions: readonly never[];
    };
    altar: {
      readonly name: "altar";
      readonly file: "altar.zip";
      readonly parts: readonly "body"[];
      readonly motions: readonly never[];
    };
    "time-machine": {
      readonly name: "time-machine";
      readonly file: "time-machine.zip";
      readonly parts: readonly "body"[];
      readonly motions: readonly never[];
    };
    "dark-web-stall": {
      readonly name: "dark-web-stall";
      readonly file: "dark-web-stall.zip";
      readonly parts: readonly "body"[];
      readonly motions: readonly never[];
    };
    "backroom-door": {
      readonly name: "backroom-door";
      readonly file: "backroom-door.zip";
      readonly parts: readonly "body"[];
      readonly motions: readonly never[];
    };
  }
}
