import type { Dim3 } from "./level-data";
import { heightAt, type TerrainConfig } from "./noise";

export const VOXEL_AIR = 0;
export const VOXEL_GRASS = 1;
export const VOXEL_DIRT = 2;
export const VOXEL_WATER = 3;

/**
 * How many rows of extra voxels each block stores beyond its interior volume,
 * on the west/east and south/north sides (never vertically — blocks don't
 * stack). The border is generated from the same world-coordinate terrain
 * function as the interior, so a block's meshes can resolve its seam faces
 * against exactly the voxels its neighbouring blocks will contain, without
 * reading the neighbours' (possibly stale) stores. Border voxels overlap the
 * neighbouring blocks' volumes and are consumed by meshing only.
 */
export const VOXEL_PADDING = 1;

/**
 * The source of truth for one block's voxels, independent of anything that
 * chunk textures. The renderer's `Level` is derived from this store by
 * `syncLevelFromStore`, which sweeps it for surface voxels. Mutating the
 * store is the hook that future runtime voxel add/remove editing builds on.
 */
export class VoxelStore {
  /** World-unit extents of the volume. */
  dims: Dim3;
  /** World units per voxel; matches the block's level-of-detail scale. */
  scale: number;
  /** Voxel counts per axis of the interior volume, excluding the border. */
  voxels: Dim3;
  /**
   * `VOXEL_PADDING` rows of meshing-only border voxels on each horizontal
   * side; `data` is laid out with that border included, so its length is
   * `(voxels[0] + 2*padding) * voxels[1] * (voxels[2] + 2*padding)`.
   */
  readonly padding: number = VOXEL_PADDING;
  data: Uint8Array;

  constructor(params: { dims: Dim3; voxels: Dim3; scale: number }) {
    this.dims = params.dims;
    this.voxels = params.voxels;
    this.scale = params.scale;
    const p = this.padding;
    this.data = new Uint8Array(
      (params.voxels[0] + 2 * p) *
        params.voxels[1] *
        (params.voxels[2] + 2 * p),
    );
  }

  /** Index of an interior voxel (including the border offset). */
  index(x: number, y: number, z: number): number {
    const [nx, ny] = this.voxels;
    const p = this.padding;
    return ((z + p) * ny + y) * (nx + 2 * p) + (x + p);
  }

  /**
   * Index of a voxel addressed in signed coordinates: `x`/`z` may be `-1`..
   * `nx`/`nz` to read the meshing border, while `y` must stay in the interior
   * range (there is no vertical border).
   */
  paddedIndex(x: number, y: number, z: number): number {
    const [nx, ny] = this.voxels;
    const p = this.padding;
    return ((z + p) * ny + y) * (nx + 2 * p) + (x + p);
  }

  /**
   * Reads a voxel at signed coordinates, including the meshing border. The
   * caller is responsible for `y` staying in range (callers that need the
   * below/above-the-world rules handle those separately).
   */
  atPadded(x: number, y: number, z: number): number {
    return this.data[this.paddedIndex(x, y, z)];
  }

  inBounds(x: number, y: number, z: number): boolean {
    return (
      x >= 0 &&
      y >= 0 &&
      z >= 0 &&
      x < this.voxels[0] &&
      y < this.voxels[1] &&
      z < this.voxels[2]
    );
  }

  get(x: number, y: number, z: number): number {
    return this.inBounds(x, y, z) ? this.data[this.index(x, y, z)] : VOXEL_AIR;
  }

  set(x: number, y: number, z: number, val: number): void {
    if (this.inBounds(x, y, z)) {
      this.data[this.index(x, y, z)] = val;
    }
  }

  reset(): void {
    this.data.fill(VOXEL_AIR);
  }
}

export type FillStoreFn = (
  store: VoxelStore,
  center: Dim3,
  config: TerrainConfig,
) => void;

/**
 * Fills an existing `store` with solid terrain columns derived from the
 * shared noise height field sampled at the block's absolute world xz (so
 * neighbouring blocks meet seamlessly). Each column is solid from the block
 * floor up to the noise height; the top voxel is grass and everything below
 * is dirt. When `config.seaLevel` is set, the air above columns that dip
 * below it is filled with water up to sea level.
 *
 * The 1-voxel meshing border is generated by the same per-column rule at the
 * world positions just outside the block, so the border always matches what
 * the neighbouring blocks will contain — seam faces are culled without ever
 * reading a neighbour's store.
 */
export const fillStore = (
  store: VoxelStore,
  center: Dim3,
  config: TerrainConfig,
): void => {
  store.reset();
  const voxelSize = store.scale;
  const [vxN, vyN, vzN] = store.voxels;
  const p = store.padding;
  const seaLevelVoxel =
    config.seaLevel === undefined
      ? undefined
      : Math.round(vyN / 2 + config.seaLevel / voxelSize);
  /**
   * Writes one column (signed `vx`/`vz`, sweeping `-1..vxN`/`-1..vzN` for the
   * border) through the padded layout.
   */
  const writeColumn = (vx: number, vz: number): void => {
    const worldX = center[0] + (vx + 0.5 - vxN / 2) * voxelSize;
    const worldZ = center[2] + (vz + 0.5 - vzN / 2) * voxelSize;
    const height = heightAt(worldX, worldZ, config);
    const top = Math.max(
      0,
      Math.min(vyN - 1, Math.round(vyN / 2 + height / voxelSize)),
    );
    for (let vy = 0; vy <= top; ++vy) {
      store.data[store.paddedIndex(vx, vy, vz)] =
        vy === top ? VOXEL_GRASS : VOXEL_DIRT;
    }
    if (seaLevelVoxel !== undefined) {
      const waterTop = top + 1;
      const waterBottom = Math.min(seaLevelVoxel, vyN - 1);
      for (let vy = waterTop; vy <= waterBottom; ++vy) {
        store.data[store.paddedIndex(vx, vy, vz)] = VOXEL_WATER;
      }
    }
  };
  for (let vz = -p; vz < vzN + p; ++vz) {
    for (let vx = -p; vx < vxN + p; ++vx) {
      writeColumn(vx, vz);
    }
  }
};
