// Generator for `demo-scripts/models.d.ts`: the `ModelsByName` augmentation
// (ADR 0050) every built-in demo script's own `tsc` check needs to see
// `createNpc`/`createProp` typed against the demo suite's real, attached
// models, the same way the live place editor generates one for a creator's
// own place from that place's actual model bytes. Every demo's model list
// (`demo-scripts/model-lists.ts`) is read here, deduplicated, and each file's
// real bytes are decoded from `public/models/` — the same folder every demo
// reads them from at run time — so this file is a pure function of what is
// already checked into the repository, never hand-typed. Run with
// `npx tsx tools/generate-demo-model-dts.ts` from this app after adding or
// changing a demo's model list, and commit the result alongside it — plain
// `node --experimental-transform-types` cannot resolve this project's
// extensionless relative imports (`moduleResolution: bundler`), only a
// bundler-aware runner like `tsx` can.
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { generateProjectModelsDts } from "../src/places/model-dts.ts";
import type { AttachedModel } from "../src/places/project.ts";
import {
  BALDI_MODELS,
  CUBE_CAVERN_MODELS,
  DONT_POOP_MODELS,
  DUSTY_TRIP_MODELS,
  GASA4_MODELS,
  LATE_TO_SCHOOL_MODELS,
  ZOMBIES_MANSION_MODELS,
  ZOMBIES_MODELS,
} from "../src/places/demo-scripts/model-lists.ts";

const here = dirname(fileURLToPath(import.meta.url));
const modelsDir = join(here, "..", "public", "models");
const outFile = join(
  here,
  "..",
  "src",
  "places",
  "demo-scripts",
  "models.d.ts",
);

const files = [
  ...new Set([
    ...GASA4_MODELS,
    ...LATE_TO_SCHOOL_MODELS,
    ...ZOMBIES_MODELS,
    ...ZOMBIES_MANSION_MODELS,
    ...DONT_POOP_MODELS,
    ...DUSTY_TRIP_MODELS,
    ...BALDI_MODELS,
    ...CUBE_CAVERN_MODELS,
  ]),
];

const models: Record<string, AttachedModel> = {};
for (const file of files) {
  models[file] = { bytes: new Uint8Array(readFileSync(join(modelsDir, file))) };
}

const dts = await generateProjectModelsDts(models);
writeFileSync(
  outFile,
  `// Generated by \`tools/generate-demo-model-dts.ts\` — do not hand-edit.
// Stands in for the \`models.d.ts\` augmentation the real place editor
// generates live from a place's own attached model bytes (\`model-dts.ts\`,
// ADR 0050), so every built-in demo script — an ordinary source file in this
// project, not only something loaded through the editor — type-checks the
// same way any other file here does. Covers every model any built-in demo
// attaches, deduplicated, since they are all checked as part of the same
// program; a model two demos share (e.g. \`counter.zip\`) contributes one
// identical entry, which TypeScript's declaration merging accepts without
// conflict only because both demos read the exact same file.
${dts}`,
);
