// The "voxelscape" module's ambient types (ADR 0050): the one place a place
// script places and moves a figure wearing an attached model, whether or not
// a given script does either. `tsc` sees this file as part of the app's own
// program, so every demo script that imports "voxelscape" type-checks
// against it directly; `project.ts` reads it back as text
// (`VOXELSCAPE_TYPES`) to feed the editor's language worker the same
// declaration for a creator's own scripts.
//
// `ModelsByName` starts empty here and is filled in two different ways for
// two different readers of this same declaration: a place's own attached
// models augment it live, generated by `model-dts.ts` into `models.d.ts`
// (never a project file a creator can open); this app's own demo scripts
// augment it with a small checked-in file per model they use (e.g.
// `demo-scripts/zombie-model.d.ts`), so `tsc` can check them the same way.
// Declaration merging is what makes both of those additive rather than
// something this file has to know about in advance.
declare module "voxelscape" {
  /** What a model is made of, keyed by name in `ModelsByName`. */
  export interface ModelDescriptor {
    readonly name: string;
    readonly file: string;
    readonly parts: readonly string[];
    readonly motions: readonly string[];
  }

  /** Every model this place carries, keyed by the bare name `createNpc`/`createProp` take — empty until augmented. */
  export interface ModelsByName {}

  /** Where a figure stands and faces, over the id/model a create call also takes. */
  interface FigurePlacement {
    x: number;
    z: number;
    y?: number;
    yaw?: number;
  }

  /** A figure's placement, re-sent on `move`. `live` marks a position the script computed itself as the figure's current owner, to broadcast to other peers rather than leave for each of them to compute independently — see the "npc" effect's own `live` field, which this passes straight through, and defaults to true. A prop, which has no such field, ignores it. */
  interface FigureMove extends FigurePlacement {
    live?: boolean;
  }

  /**
   * An NPC placed and moved through the "npc"/"npc-remove"/"npc-die"
   * effects, as `createNpc` hands it back. Owns only where it stands and
   * dispatching its own placement — a script's own bookkeeping (health, AI
   * state, and the rest) stays the script's own.
   */
  export interface NpcHandle<M extends ModelDescriptor> {
    readonly model: M;
    readonly id: string;
    /** Where the figure currently stands — set by `createNpc` and by `move`, never by anything else. */
    readonly x: number;
    readonly z: number;
    /** Feet height in world units, or undefined to leave it grounded. */
    readonly y?: number;
    /** Which way the figure currently faces, in radians. */
    readonly yaw: number;
    /** Moves the figure and re-dispatches its placement. */
    move(options: FigureMove): void;
    /** Removes the NPC outright — no death fall. */
    remove(): void;
    /** Plays a death fall in place of an outright removal, then forgets it the same way. */
    die(): void;
  }

  interface CreateNpcOptions<
    K extends keyof ModelsByName,
  > extends FigurePlacement {
    /** Which model this NPC wears. */
    model: K;
    id: string;
    /** Shown to players, e.g. "Zombie" — the model it wears is a separate thing from what it is called. */
    name?: string;
    /** Reads the model live from its own `at://` address instead of the place's bundled files. */
    modelUri?: string;
  }

  /**
   * Places an NPC wearing the model named `options.model` — a name
   * `ModelsByName` does not carry is refused at the type level; a name this
   * place does not actually attach is refused at run time, inside
   * `createNpc` itself, the moment a script calls it. `id` is never
   * generated: every peer replaying the same script must compute the exact
   * same id independently (ADR 0026), so it has to come from the caller's
   * own deterministic address, the way the Zombies demo derives one from its
   * population seed and spawn cell.
   */
  export function createNpc<K extends keyof ModelsByName>(
    options: CreateNpcOptions<K>,
  ): NpcHandle<ModelsByName[K]>;

  /** A prop placed through the "prop"/"prop-remove" effects, as `createProp` hands it back. */
  export interface PropHandle<M extends ModelDescriptor> {
    readonly model: M;
    readonly id: string;
    readonly x: number;
    readonly z: number;
    readonly y?: number;
    readonly yaw: number;
    move(options: FigureMove): void;
    remove(): void;
  }

  interface CreatePropOptions<
    K extends keyof ModelsByName,
  > extends FigurePlacement {
    model: K;
    id: string;
    name?: string;
    height?: number;
    solid?: boolean;
    hazard?: boolean;
    conveyor?: { vx: number; vz: number };
  }

  /** Places a prop wearing the model named `options.model`; see `createNpc` for how a name resolves and why `id` is never generated. */
  export function createProp<K extends keyof ModelsByName>(
    options: CreatePropOptions<K>,
  ): PropHandle<ModelsByName[K]>;
}
