// The `"voxelscape"` module's ambient types: the one place every function
// `quickjs-sandbox.ts` binds is typed, whether or not a given script calls
// it, alongside `createNpc`/`createProp` (ADR 0050) for placing and moving a
// figure wearing an attached model. `tsc` sees this file as part of the app's
// own program, so every demo script that imports "voxelscape" type-checks
// against it directly; `project.ts` reads it back as text
// (`VOXELSCAPE_TYPES`) to feed the editor's language worker the same
// declaration for a creator's own scripts. `PlaceEditorPanes.tsx` feeds the
// worker `effects.ts`, `cutscene.ts`, and `motion.ts` too, so `dispatch`'s
// payload type resolves the same way there as it does for `tsc`.
//
// `ModelsByName` starts empty here and is filled in two different ways for
// two different readers of this same declaration: a place's own attached
// models augment it live, generated by `model-dts.ts` into `models.d.ts`
// (never a project file a creator can open); this app's own demo scripts
// augment it with a small checked-in file per model they use (e.g.
// `demo-scripts/models.d.ts`), so `tsc` can check them the same way.
// Declaration merging is what makes both of those additive rather than
// something this file has to know about in advance.
//
// This file carries no top-level `import` of its own — an inline
// `import("./effects")` type reaches the same file without one — because a
// top-level import would turn `declare module "voxelscape"` below from a
// fresh ambient module declaration into an augmentation of one that would
// then need to already exist elsewhere.
declare module "voxelscape" {
  type EffectTag = import("./effects").EffectTag;
  type ParsedEffect = import("./effects").ParsedEffect;
  /** One parsed fact `onTick` hands a script, exactly as the trusted side authored it. */
  export type ScriptEvent = import("./events").ScriptEvent;

  /** The shape `tag` validates against, per `effects.ts`'s own `ParsedEffect`. */
  type PayloadFor<T extends EffectTag> = Extract<
    ParsedEffect,
    { tag: T }
  >["payload"];

  /**
   * Queues one effect for the trusted side to validate and apply. `payload`
   * is typed to the shape `tag` itself validates against — `dispatch`
   * stringifies it before it crosses the sandbox boundary.
   */
  export function dispatch<T extends EffectTag>(
    tag: T,
    payload: PayloadFor<T>,
  ): void;
  export function log(line: string): void;
  export function now(): number;
  export function endings(): string;
  /** Every player's live position: the local player first, then connected peers. */
  export function players(): string;
  /** The terrain surface at (x, z). */
  export function heightAt(x: number, z: number): number;
  /** Whether (x, y, z) is inside solid ground. */
  export function solidAt(x: number, y: number, z: number): boolean;
  /** Whether (x, y, z) is water. */
  export function waterAt(x: number, y: number, z: number): boolean;
  /**
   * Registers a handler the world calls each step with the shared clock and
   * the facts since the last step, already parsed — `events` is the exact
   * `ScriptEvent[]` the trusted side authored, not the JSON text it crossed
   * the sandbox boundary as.
   */
  export function onTick(
    fn: (clockMs: number, events: ScriptEvent[]) => void,
  ): void;
  export function onPlan(fn: (contextJson: string) => string): void;
  export const blocks: Record<string, number>;

  /** What a model is made of, keyed by name in `ModelsByName`. */
  export interface ModelDescriptor {
    readonly name: string;
    readonly file: string;
    readonly parts: readonly string[];
    readonly motions: readonly string[];
  }

  /** Every model this place carries, keyed by the bare name `createNpc`/`createProp` take — empty until augmented. */
  export interface ModelsByName {}

  /** Where a figure stands and faces, over the id/model a create call also takes. */
  interface FigurePlacement {
    x: number;
    z: number;
    y?: number;
    yaw?: number;
  }

  /** A figure's placement, re-sent on `move`. `live` marks a position the script computed itself as the figure's current owner, to broadcast to other peers rather than leave for each of them to compute independently — see the "npc" effect's own `live` field, which this passes straight through, and defaults to true. A prop, which has no such field, ignores it. */
  interface FigureMove extends FigurePlacement {
    live?: boolean;
  }

  /**
   * An NPC placed and moved through the "npc"/"npc-remove"/"npc-die"
   * effects, as `createNpc` hands it back. Owns only where it stands and
   * dispatching its own placement — a script's own bookkeeping (health, AI
   * state, and the rest) stays the script's own. `model` is `undefined` for
   * an NPC `createNpc` placed with no `model` option, left for the world to
   * draw with its own default figure.
   */
  export interface NpcHandle<M extends ModelDescriptor | undefined> {
    readonly model: M;
    readonly id: string;
    /** Where the figure currently stands — set by `createNpc` and by `move`, never by anything else. */
    readonly x: number;
    readonly z: number;
    /** Feet height in world units, or undefined to leave it grounded. */
    readonly y?: number;
    /** Which way the figure currently faces, in radians. */
    readonly yaw: number;
    /** Moves the figure and re-dispatches its placement. */
    move(options: FigureMove): void;
    /** Removes the NPC outright — no death fall. */
    remove(): void;
    /** Plays a death fall in place of an outright removal, then forgets it the same way. */
    die(): void;
  }

  interface CreateNpcOptions<
    K extends keyof ModelsByName | undefined,
  > extends FigurePlacement {
    /** Which model this NPC wears; omit it to leave the world drawing its own default figure. */
    model?: K;
    id: string;
    /** Shown to players, e.g. "Zombie" — the model it wears is a separate thing from what it is called. */
    name?: string;
    /** Reads the model live from its own `at://` address instead of the place's bundled files. */
    modelUri?: string;
  }

  /**
   * Places an NPC wearing the model named `options.model` — a name
   * `ModelsByName` does not carry is refused at the type level; a name this
   * place does not actually attach is refused at run time, inside
   * `createNpc` itself, the moment a script calls it. Omitting `model`
   * entirely leaves the world drawing its own default figure, the same way
   * omitting it from a hand-written "npc" effect already does. `id` is never
   * generated: every peer replaying the same script must compute the exact
   * same id independently (ADR 0026), so it has to come from the caller's
   * own deterministic address, the way the Zombies demo derives one from its
   * population seed and spawn cell.
   */
  export function createNpc<
    K extends keyof ModelsByName | undefined = undefined,
  >(
    options: CreateNpcOptions<K>,
  ): NpcHandle<K extends keyof ModelsByName ? ModelsByName[K] : undefined>;

  /** A prop placed through the "prop"/"prop-remove" effects, as `createProp` hands it back. */
  export interface PropHandle<M extends ModelDescriptor> {
    readonly model: M;
    readonly id: string;
    readonly x: number;
    readonly z: number;
    readonly y?: number;
    readonly yaw: number;
    move(options: FigureMove): void;
    remove(): void;
  }

  interface CreatePropOptions<
    K extends keyof ModelsByName,
  > extends FigurePlacement {
    model: K;
    id: string;
    name?: string;
    height?: number;
    solid?: boolean;
    hazard?: boolean;
    conveyor?: { vx: number; vz: number };
    /** A path and spin the prop follows over the shared clock, in place of `move`. */
    motion?: import("./motion").MotionSpec;
  }

  /** Places a prop wearing the model named `options.model`; see `createNpc` for how a name resolves and why `id` is never generated. */
  export function createProp<K extends keyof ModelsByName>(
    options: CreatePropOptions<K>,
  ): PropHandle<ModelsByName[K]>;
}
