// The sample voxel model that ships with the editor, for showing how a
// stacker figure is hung off an imported skeleton. It is generated from the
// Fox rig by `scripts/make-models.mjs`, one box a bone, named after the bone
// it belongs on, so "Auto-bind" lands every part with nothing to line up.
export interface BundledModel {
  /** What to call the sample in the panel. */
  label: string;
  /** The figure zip under the public folder. */
  path: string;
  /** The glTF whose skeleton the model is drawn for. */
  skeletonPath: string;
  /** Who made the source art and under what licence. */
  credits: string;
}

export const BUNDLED_MODELS: BundledModel[] = [
  {
    label: "Human (skeleton + model)",
    path: "models/human.zip",
    skeletonPath: "animations/human.glb",
    credits:
      "Rig by Kay Lousberg (CC0); voxel figure generated by scripts/make-models.mjs",
  },
  {
    label: "Fox (skeleton + model)",
    path: "models/fox.zip",
    skeletonPath: "animations/Fox.glb",
    credits:
      "Fox by PixelMannen, CC0; voxel figure generated by scripts/make-models.mjs",
  },
];

/** The address a public asset is served from, wherever the app is hosted. */
export function modelUrl(path: string): string {
  return `${import.meta.env.BASE_URL}${path}`;
}
